<?php

namespace TV\ChefBundle\Repository;

/**
 * NotebookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotebookRepository extends \Doctrine\ORM\EntityRepository
{
}
