<?php

namespace TV\ChefBundle\Repository;

/**
 * SearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearch($user)
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.ip = :user')
            ->setParameter('user', $user)
            ->orderBy('a.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
        ;
        return $query->getSingleResult();
    }
}
