<?php

namespace TV\ChefBundle\Repository;

/**
 * QuantityTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeQuantityRepository extends \Doctrine\ORM\EntityRepository
{
}
