tv_chef_homepage:
    path:     /
    defaults: 
        _controller: TVChefBundle:Home:index
        
tv_chef_recipe_index:
    path:    /recipe/{page}
    defaults: 
        _controller: TVChefBundle:Recipe:index
        page: 1
    requirements:
        page: \d*
        
tv_chef_recipe_view:
    path:    /recipe/view/{id}
    defaults: 
        _controller: TVChefBundle:Recipe:view
    requirements:
        id: \d+
        
tv_chef_recipe_add:
    path:    /recipe/add
    defaults: 
        _controller: TVChefBundle:Recipe:add
        
tv_chef_recipe_edit:
    path:    /recipe/edit/{id}
    defaults: 
        _controller: TVChefBundle:Recipe:edit
    requirements:
        id: \d+
        
tv_chef_recipe_delete:
    path:    /recipe/delete/{id}
    defaults: 
        _controller: TVChefBundle:Recipe:delete
    requirements:
        id: \d+
        
tv_chef_recipe_note:
    path:    /recipe/note/{id}
    defaults: 
        _controller: TVChefBundle:Recipe:note
    requirements:
        id: \d+
        
tv_chef_filter_select:
    path:      /recipes/select/{page}
    defaults:
        _controller: TVChefBundle:Filter:select
        page:  1
    requirements:
        _method: GET
        page: \d+

tv_chef_search_select:
    path:      /recipes/search/{page}
    defaults:
        _controller: TVChefBundle:Search:select
        page:  1
    requirements:
        _method: POST
        page: \d+
        
tv_chef_search_autocomplete:
    path: /search-autocomplete
    defaults: 
        _controller: TVChefBundle:Search:autocomplete
    requirements:
        _method: POST
        
tv_chef_ingredient_add:
    path:    /ingredient/add/{id}
    defaults: 
        _controller: TVChefBundle:Ingredient:add
    requirements:
        id: \d+
        
tv_chef_ingredient_edit:
    path:   /recipe/{id_recipe}/ingredient/edit/{id}
    defaults:
        _controller: TVChefBundle:Ingredient:edit
    requirements:
        id: \d+
        id_recipe: \d+
        
tv_chef_ingredient_delete:
    path:   /recipe/{id_recipe}/ingredient/delete/{id}
    defaults:
        _controller: TVChefBundle:Ingredient:delete
    requirements:
        id: \d+
        
tv_chef_step_add:
    path:    /step/add/{id}
    defaults: 
        _controller: TVChefBundle:Step:add
    requirements:
        id: \d+
        
tv_chef_step_edit:
    path:   /recipe/{id_recipe}/step/edit/{id}
    defaults:
        _controller: TVChefBundle:Step:edit
    requirements:
        id: \d+
        id_recipe: \d+
        
tv_chef_step_delete:
    path:   /recipe/{id_recipe}/step/delete/{id}
    defaults:
        _controller: TVChefBundle:Step:delete
    requirements:
        id: \d+
        
tv_chef_notebook_index:
    path: /recipe/notebook/{page}
    defaults:
        _controller: TVChefBundle:Notebook:index
        page: 1
    requirements:
        page: \d+
        
tv_chef_notebook_add:
    path: /recipe/{id}/notebook/add
    defaults:
        _controller: TVChefBundle:Notebook:add
    requirements:
        id: \d+
        
tv_chef_notebook_delete:
    path: /recipe/{id}/notebook/delete
    defaults:
        _controller: TVChefBundle:Notebook:delete
    requirements:
        id: \d+
        
tv_chef_liste_index:
    path: recipe/liste/
    defaults:
        _controller: TVChefBundle:Liste:index
        
tv_chef_liste_add:
    path: /recipe/{id}/liste/add
    defaults:
        _controller: TVChefBundle:Liste:add
    requirements:
        id: \d+
        
tv_chef_liste_delete:
    path: /liste/delete/{id}
    defaults:
        _controller: TVChefBundle:Liste:delete
    requirements:
        id: \d+
        
tv_chef_liste_delete_ingredient:
    path: /liste/{id_liste}/delete/ingredient/{id}
    defaults:
        _controller: TVChefBundle:Liste:deleteIngredient
    requirements:
        id: \d+
        
tv_chef_recipe_printable:
    path: /recipe/{id}/printable
    defaults:
        _controller: TVChefBundle:Recipe:printable
    requirements:
        id: \d+
