<?php

namespace TV\UserBundle\Repository;

/**
 * NoteUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteUserRepository extends \Doctrine\ORM\EntityRepository
{
}
